[package]
name = "iced-bar"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0

[dependencies]
chrono = "0.4.41"
iced_layershell = "0.13.6"
iced = {version = "0.13.1", features = ["tokio"]}
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", branch = "master" }
